<a href="https://colab.research.google.com/github/aechu77/data_science_lab10/blob/main/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# a) Create a 3x3 matrix
A = np.array([[2, 1, 3],
              [4, 1, 6],
              [7, 8, 9]])

print("Matrix A:")
print(A)

# Compute determinant
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:")
print(det_A)

# b) Find inverse of the matrix
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("\nInverse of Matrix A:")
    print(inv_A)
else:
    print("\nMatrix A is singular and does not have an inverse.")

# c) Solve system of linear equations
# 2x + 3y = 10
# 4x + 5y = 20

B = np.array([[2, 3],
              [4, 5]])   # Coefficient matrix

C = np.array([10, 20])   # Constant matrix

solution = np.linalg.solve(B, C)

print("\nSolution of the linear equations:")
print("x =", solution[0])
print("y =", solution[1])

Matrix A:
[[2 1 3]
 [4 1 6]
 [7 8 9]]

Determinant of Matrix A:
3.000000000000002

Inverse of Matrix A:
[[-13.           5.           1.        ]
 [  2.          -1.          -0.        ]
 [  8.33333333  -3.          -0.66666667]]

Solution of the linear equations:
x = 5.0
y = 0.0
